dist: trusty
language: go
go:
  - 1.6
  - 1.7
  - 1.8
env:
  - VER=4.1
  - VER=5.0
  - VER=5.1
before_install:
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish${VER/./}/script.deb.sh | sudo bash
  - sudo apt-get install varnish=${VER}.* varnish-dev=${VER}.*
  - sudo usermod -a -G varnish $USER
script:
  - sudo -E su $USER -c "$(which go) test -v"
