name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go: ['1.13', '1.14']
        varnish: ['6.0', '6.3', '6.4']
    name: Go ${{ matrix.go }} - Varnish ${{ matrix.varnish }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Set up Varnish
      run: |
        VER=`echo ${{ matrix.varnish }} | sed 's/\.//'`
        curl -s https://packagecloud.io/install/repositories/varnishcache/varnish${VER}/script.deb.sh | sudo bash
        sudo apt-get install varnish=${{ matrix.varnish }}.* varnish-dev=${{ matrix.varnish }}.*
        sudo usermod -a -G varnish $USER
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        sudo -E su $USER -c "go test -v"
        sudo -E su $USER -c "go vet -unsafeptr=false"
