name: ci

on: [push, pull_request]

jobs:
  test:

    strategy:
      matrix:
        go: ['1.19', '1.20']
        varnish: ['6.0', '7.2', '7.3']

    name: Go ${{ matrix.go }} - Varnish ${{ matrix.varnish }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - uses: varnishcache-friends/setup-varnish@v1
      with:
        version: ${{ matrix.varnish }}
    - uses: actions/checkout@v3
    - run: |
        sudo install -d -o $USER /var/lib/varnish
        /usr/local/sbin/varnishd -a :1234 -b :1235
        go test -v
        go vet -unsafeptr=false
